from core import Sprite

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Space Impact"

MAP_VERTICAL_BOUND_OFFSET = 100
MAP_HORIZONTAL_BOUND_OFFSET = 0
MAP_TOP_BOUND = WINDOW_HEIGHT - (WINDOW_HEIGHT - MAP_VERTICAL_BOUND_OFFSET)
MAP_BOTTOM_BOUND = WINDOW_HEIGHT - MAP_VERTICAL_BOUND_OFFSET
MAP_LEFT_BOUND = WINDOW_WIDTH - (WINDOW_WIDTH - MAP_HORIZONTAL_BOUND_OFFSET)
MAP_RIGHT_BOUND = WINDOW_WIDTH - MAP_HORIZONTAL_BOUND_OFFSET

ROCKET_RECT_WIDTH = 10 * 12
ROCKET_RECT_HEIGHT = 7 * 12
ROCKET_RECT_COLOR = (0, 100, 0)
ROCKET_ANIMATIONS = [Sprite("textures/rocket.png", 144, 144)]

STAR_SHIP_RECT_WIDTH = 144
STAR_SHIP_RECT_HEIGHT = 144
STAR_SHIP_RECT_COLOR = (255, 0, 0)
STAR_SHIP_ANIMATIONS = [Sprite("textures/comet_1.png", 144, 144), Sprite("textures/comet_2.png", 144, 144)]
STAR_SHIP_ANIMATIONS_INTERVAL = 100

PLAYER_SPAWN_X = 10
PLAYER_SPAWN_Y = MAP_TOP_BOUND + ROCKET_RECT_HEIGHT
PLAYER_SPEED = 5

UP = "up"
LEFT = "left"
RIGHT = "right"
DOWN = "down"

DEBUG_SHOW_RECTS = True