from core import Sprite, TextureAtlas, Font, Text

# CONFIGURATION FILE FOR Py-Space-Impact
# Edit anything you like
# DO NOT DELETE OR RENAME VARIABLES, WILL CRASH

WINDOW_WIDTH = 1140
WINDOW_HEIGHT = 720
WINDOW_TITLE = "スーペース・イムパクト"

MAP_VERTICAL_BOUND_OFFSET = 100
MAP_HORIZONTAL_BOUND_OFFSET = 0
MAP_TOP_BOUND = WINDOW_HEIGHT - (WINDOW_HEIGHT - MAP_VERTICAL_BOUND_OFFSET)
MAP_BOTTOM_BOUND = WINDOW_HEIGHT - MAP_VERTICAL_BOUND_OFFSET
MAP_LEFT_BOUND = WINDOW_WIDTH - (WINDOW_WIDTH - MAP_HORIZONTAL_BOUND_OFFSET)
MAP_RIGHT_BOUND = WINDOW_WIDTH - MAP_HORIZONTAL_BOUND_OFFSET
MAP_GAME_FIELD_WIDTH = MAP_RIGHT_BOUND - MAP_LEFT_BOUND
MAP_GAME_FIELD_HEIGHT = MAP_BOTTOM_BOUND - MAP_TOP_BOUND

SPRITE_SMALL_WIDTH = 12 * 12
SPRITE_SMALL_HEIGHT = 12 * 12
SPRITE_LARGE_WIDTH = 36 * 12
SPRITE_LARGE_HEIGHT = 36 * 12
SPRITE_HUGE_WIDTH = 48 * 12
SPRITE_HUGE_HEIGHT = 48 * 12

BATTLE_SHIP_RECT_WIDTH = 10 * 12
BATTLE_SHIP_RECT_HEIGHT = 7 * 12
BATTLE_SHIP_RECT_COLOR = (0, 100, 0)
BATTLE_SHIP_ANIMATIONS = [Sprite.load("textures/battleship.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]

# █▀▀ █▄░█ █▀▀ █▀▄▀█ █ █▀▀ █▀
# ██▄ █░▀█ ██▄ █░▀░█ █ ██▄ ▄█

COMET_RECT_WIDTH = 10 * 12
COMET_RECT_HEIGHT = 5 * 12
COMET_RECT_COLOR = (255, 0, 0)
COMET_ANIMATIONS = [Sprite.load("textures/comet1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/comet2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
COMET_ANIMATIONS_INTERVAL = 100
COMET_HEALTH = 1
COMET_HIT_REWARD = 5
COMET_POP_REWARD = 5
COMET_SHOOT_CHANCE = 16

SHUTTLE_RECT_WIDTH = 8 * 12
SHUTTLE_RECT_HEIGHT = 5 * 12
SHUTTLE_RECT_COLOR = (255, 0, 0)
SHUTTLE_ANIMATIONS = [Sprite.load("textures/shuttle1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/shuttle2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/shuttle3.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
SHUTTLE_ANIMATIONS_INTERVAL = 100
SHUTTLE_HEALTH = 1
SHUTTLE_HIT_REWARD = 5
SHUTTLE_POP_REWARD = 5
SHUTTLE_SHOOT_CHANCE = 16

VSHIP_RECT_WIDTH = 6 * 12
VSHIP_RECT_HEIGHT = 7 * 12
VSHIP_RECT_COLOR = (255, 0, 0)
VSHIP_ANIMATIONS = [Sprite.load("textures/vship1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/vship2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
VSHIP_ANIMATIONS_INTERVAL = 100
VSHIP_HEALTH = 1
VSHIP_HIT_REWARD = 5
VSHIP_POP_REWARD = 5
VSHIP_SHOOT_CHANCE = 16

ROCKET_RECT_WIDTH = 10 * 12
ROCKET_RECT_HEIGHT = 5 * 12
ROCKET_RECT_COLOR = (255, 0, 0)
ROCKET_ANIMATIONS = [Sprite.load("textures/rocket1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/rocket2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
ROCKET_ANIMATIONS_INTERVAL = 100
ROCKET_HEALTH = 3
ROCKET_HIT_REWARD = 5
ROCKET_POP_REWARD = 5
ROCKET_SHOOT_CHANCE = 16

ACORN_RECT_WIDTH = 8 * 12 - 4
ACORN_RECT_HEIGHT = 5 * 12 - 4
ACORN_RECT_COLOR = (255, 0, 0)
ACORN_ANIMATIONS = [Sprite.load("textures/acorn.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
ACORN_ANIMATIONS_INTERVAL = 100
ACORN_HEALTH = 1
ACORN_HIT_REWARD = 5
ACORN_POP_REWARD = 5
ACORN_SHOOT_CHANCE = 16

SNAKE_RECT_WIDTH = 10 * 12
SNAKE_RECT_HEIGHT = 5 * 12
SNAKE_RECT_COLOR = (255, 0, 0)
SNAKE_ANIMATIONS = [Sprite.load("textures/snake1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/snake2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
SNAKE_ANIMATIONS_INTERVAL = 100
SNAKE_HEALTH = 1
SNAKE_HIT_REWARD = 5
SNAKE_POP_REWARD = 5
SNAKE_SHOOT_CHANCE = 16

DRONE_RECT_WIDTH = 7 * 12
DRONE_RECT_HEIGHT = 7 * 12
DRONE_RECT_COLOR = (255, 0, 0)
DRONE_ANIMATIONS = [Sprite.load("textures/drone.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
DRONE_ANIMATIONS_INTERVAL = 100
DRONE_HEALTH = 10
DRONE_HIT_REWARD = 5
DRONE_POP_REWARD = 5
DRONE_SHOOT_CHANCE = 0

DRONE_MINION_HEALTH = 13
DRONE_MINION_HIT_REWARD = 0
DRONE_MINION_POP_REWARD = 0

VIRUS_RECT_WIDTH = 7 * 12
VIRUS_RECT_HEIGHT = 9 * 12
VIRUS_RECT_COLOR = (255, 0, 0)
VIRUS_ANIMATIONS = [Sprite.load("textures/virus.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
VIRUS_ANIMATIONS_INTERVAL = 100
VIRUS_HEALTH = 25
VIRUS_HIT_REWARD = 5
VIRUS_POP_REWARD = 5
VIRUS_SHOOT_CHANCE = 0

COCKROACH_RECT_WIDTH = 12 * 12
COCKROACH_RECT_HEIGHT = 7 * 12
COCKROACH_RECT_COLOR = (255, 0, 0)
COCKROACH_ANIMATIONS = [Sprite.load("textures/cockroach_1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/cockroach_2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
COCKROACH_ANIMATIONS_INTERVAL = 100
COCKROACH_HEALTH = 3
COCKROACH_HIT_REWARD = 5
COCKROACH_POP_REWARD = 5
COCKROACH_SHOOT_CHANCE = 16

BEAN_RECT_WIDTH = 5 * 12
BEAN_RECT_HEIGHT = 4 * 12
BEAN_RECT_COLOR = (255, 0, 0)
BEAN_ANIMATIONS = [Sprite.load("textures/bean.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
BEAN_ANIMATIONS_INTERVAL = 100
BEAN_HEALTH = 1
BEAN_HIT_REWARD = 5
BEAN_POP_REWARD = 5
BEAN_SHOOT_CHANCE = 16


# █▄▄ █▀█ █▀ █▀ █▀▀ █▀
# █▄█ █▄█ ▄█ ▄█ ██▄ ▄█

ALIEN_JELLYFISH_BOSS_RECT_WIDTH = 20 * 12
ALIEN_JELLYFISH_BOSS_RECT_HEIGHT = 25 * 12
ALIEN_JELLYFISH_BOSS_RECT_COLOR = (255, 0, 0)
ALIEN_JELLYFISH_BOSS_ANIMATIONS = [Sprite.load("textures/alien_jellyfish1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/alien_jellyfish2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
ALIEN_JELLYFISH_BOSS_ANIMATIONS_INTERVAL = 250
ALIEN_JELLYFISH_BOSS_HEALTH = 60
ALIEN_JELLYFISH_BOSS_HIT_REWARD = 5
ALIEN_JELLYFISH_BOSS_POP_REWARD = 100
ALIEN_JELLYFISH_BOSS_SHOOT_CHANCE = 20
# OTHER
ALIEN_JELLYFISH_BOSS_VERTICAL_STOP_SPEED = 4

PYTHON_BOSS_RECT_WIDTH = 23 * 12
PYTHON_BOSS_RECT_HEIGHT = 21 * 12
PYTHON_BOSS_RECT_COLOR = (255, 0, 0)
PYTHON_BOSS_ANIMATIONS = [Sprite.load("textures/python1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/python2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
PYTHON_BOSS_ANIMATIONS_INTERVAL = 250
PYTHON_BOSS_HEALTH = 70
PYTHON_BOSS_HIT_REWARD = 10
PYTHON_BOSS_POP_REWARD = 150
PYTHON_BOSS_SHOOT_CHANCE = 37
# OTHER
PYTHON_BOSS_VERTICAL_STOP_SPEED = 4

PIRANHA_BOSS_RECT_WIDTH = 22 * 12
PIRANHA_BOSS_RECT_HEIGHT = 20 * 12
PIRANHA_BOSS_RECT_COLOR = (255, 0, 0)
PIRANHA_BOSS_ANIMATIONS = [Sprite.load("textures/piranha1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/piranha2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
PIRANHA_BOSS_ANIMATIONS_INTERVAL = 250
PIRANHA_BOSS_HEALTH = 90
PIRANHA_BOSS_HIT_REWARD = 10
PIRANHA_BOSS_POP_REWARD = 175
PIRANHA_BOSS_SHOOT_CHANCE = 37
# ABILITY
PIRANHA_BOSS_ABILITY_COOLDOWN = 7000
PIRANHA_BOSS_ABILITY_POSITION_PHASE_VERTICAL_SPEED = 2
PIRANHA_BOSS_ABILITY_SHOOT_CHANCE = 0
PIRANHA_BOSS_ABILITY_SHOOT_INTERVAL = 1000
PIRANHA_BOSS_ABILITY_PROJECTILES_COUNT = 5
PIRANHA_BOSS_ABILITY_PROJECTILES_COVERED_SURFACE_HEIGHT = 125
PIRANHA_BOSS_ABILITY_SHOTS_COUNT = 5
# OTHER
PIRANHA_BOSS_VERTICAL_STOP_SPEED = 4

YOTSU_BOSS_RECT_WIDTH = 16 * 12
YOTSU_BOSS_RECT_HEIGHT = 24 * 12
YOTSU_BOSS_RECT_COLOR = (255, 0, 0)
YOTSU_BOSS_ANIMATIONS = [Sprite.load("textures/yotsu1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/yotsu2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
YOTSU_BOSS_ANIMATIONS_INTERVAL = 250
YOTSU_BOSS_HEALTH = 100
YOTSU_BOSS_HIT_REWARD = 10
YOTSU_BOSS_POP_REWARD = 200
YOTSU_BOSS_SHOOT_CHANCE = 43
# ABILITY
YOTSU_BOSS_ABILITY_COOLDOWN = 7500
YOTSU_BOSS_ABILITY_DRONES_COUNT = 5
YOTSU_BOSS_ABITITY_DRONES_OFFSET = DRONE_RECT_WIDTH + 50
# OTHER
YOTSU_BOSS_VERTICAL_STOP_SPEED = 4

PUFFERFISH_BOSS_RECT_WIDTH = 19 * 12
PUFFERFISH_BOSS_RECT_HEIGHT = 21 * 12
PUFFERFISH_BOSS_RECT_COLOR = (255, 0, 0)
PUFFERFISH_BOSS_ANIMATIONS = [Sprite.load("textures/pufferfish1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/pufferfish2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
PUFFERFISH_BOSS_ANIMATIONS_INTERVAL = 250
PUFFERFISH_BOSS_HEALTH = 120
PUFFERFISH_BOSS_HIT_REWARD = 10
PUFFERFISH_BOSS_POP_REWARD = 225
PUFFERFISH_BOSS_SHOOT_CHANCE = 50
# ABILITY
PUFFERFISH_BOSS_ABILITY_COOLDOWN = 7000
PUFFERFISH_BOSS_ABILITY_CHARGE_ACCELERATION = 0.1
PUFFERFISH_BOSS_ABILITY_CHARGE_STOP_DISTANCE = 50
PUFFERFISH_BOSS_ABILITY_LEFT_STOP_X = MAP_LEFT_BOUND + PUFFERFISH_BOSS_ABILITY_CHARGE_STOP_DISTANCE
PUFFERFISH_BOSS_ABILITY_RIGHT_STOP_X = MAP_RIGHT_BOUND - PUFFERFISH_BOSS_RECT_WIDTH - PUFFERFISH_BOSS_ABILITY_CHARGE_STOP_DISTANCE
# OTHER
PUFFERFISH_BOSS_VERTICAL_STOP_SPEED = 2

SHELL_BOSS_RECT_WIDTH = 18 * 12
SHELL_BOSS_RECT_HEIGHT = 19 * 12
SHELL_BOSS_RECT_COLOR = (255, 0, 0)
SHELL_BOSS_ANIMATIONS = [Sprite.load("textures/shell1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/shell2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
SHELL_BOSS_ANIMATIONS_INTERVAL = 250
SHELL_BOSS_HEALTH = 120
SHELL_BOSS_HIT_REWARD = 10
SHELL_BOSS_POP_REWARD = 225
SHELL_BOSS_SHOOT_CHANCE = 50
# ABILITY
SHELL_BOSS_ABILITY_COOLDOWN = 5000
SHELL_BOSS_ABILITY_COCKROACH_MINIONS_COUNT = 5
SHELL_BOSS_ABILITY_COCKROACH_MINIONS_SUMMON_DELAY = 750
SHELL_BOSS_ABILITY_COCKROACH_MINION_HORIZONTAL_SPEED = 4
SHELL_BOSS_ABILITY_COCKROACH_MINION_VERTICAL_SPEED = 0
SHELL_BOSS_ABILITY_COCKROACH_MINION_HEALTH = 2
# OTHER
SHELL_BOSS_VERTICAL_STOP_SPEED = 4

SQUID_BOSS_RECT_WIDTH = 30 * 12
SQUID_BOSS_RECT_HEIGHT = 25 * 12
SQUID_BOSS_RECT_COLOR = (255, 0, 0)
SQUID_BOSS_ANIMATIONS = [Sprite.load("textures/squid1.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT), Sprite.load("textures/squid2.png", SPRITE_LARGE_WIDTH, SPRITE_LARGE_HEIGHT)]
SQUID_BOSS_ANIMATIONS_INTERVAL = 250
SQUID_BOSS_HEALTH = 150
SQUID_BOSS_HIT_REWARD = 10
SQUID_BOSS_POP_REWARD = 300
SQUID_BOSS_SHOOT_CHANCE = 100
# ABILITY
SQUID_BOSS_ABILITY_COOLDOWN = 9000
SQUID_BOSS_ABILITY_CHARGE_ACCELERATION = 0.1
SQUID_BOSS_ABILITY_CHARGE_STOP_DISTANCE = 50
SQUID_BOSS_ABILITY_RETREAT_DISTANCE = 500
SQUID_BOSS_ABILITY_RETREAT_RIGHT_STOP_X = MAP_RIGHT_BOUND + SQUID_BOSS_RECT_WIDTH + SQUID_BOSS_ABILITY_RETREAT_DISTANCE
SQUID_BOSS_ABILITY_LEFT_STOP_X = MAP_LEFT_BOUND + SQUID_BOSS_ABILITY_CHARGE_STOP_DISTANCE
SQUID_BOSS_ABILITY_RIGHT_STOP_X = MAP_RIGHT_BOUND - SQUID_BOSS_RECT_WIDTH - SQUID_BOSS_ABILITY_CHARGE_STOP_DISTANCE
# OTHER
SQUID_BOSS_VERTICAL_STOP_SPEED = 2


KRAKEN_BOSS_RECT_WIDTH = 39 * 12
KRAKEN_BOSS_RECT_HEIGHT = 38 * 12
KRAKEN_BOSS_RECT_COLOR = (255, 0, 0)
KRAKEN_BOSS_ANIMATIONS = [Sprite.load("textures/kraken.png", SPRITE_HUGE_WIDTH, SPRITE_HUGE_HEIGHT)]
KRAKEN_BOSS_ANIMATIONS_INTERVAL = 250
KRAKEN_BOSS_HEALTH = 300
KRAKEN_BOSS_HIT_REWARD = 20
KRAKEN_BOSS_POP_REWARD = 1000
KRAKEN_BOSS_SHOOT_CHANCE = 0
# OTHER
KRAKEN_BOSS_VERTICAL_STOP_SPEED = 0

# █▀█ █▀█ █▀█ ░░█ █▀▀ █▀▀ ▀█▀ █ █░░ █▀▀ █▀
# █▀▀ █▀▄ █▄█ █▄█ ██▄ █▄▄ ░█░ █ █▄▄ ██▄ ▄█

PROJECTILE_PEW_RECT_WIDTH = 3 * 12
PROJECTILE_PEW_RECT_HEIGHT = 1 * 12
PROJECTILE_PEW_RECT_COLOR = (0, 59, 255)
PROJECTILE_PEW_ANIMATIONS = [Sprite.load("textures/pew.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
PROJECTILE_PEW_HORIZONTAL_SPEED = 4
PROJECTILE_PEW_VERTICAL_SPEED = 0
PROJECTILE_PEW_HEALTH = 1
PROJECTILE_PEW_DAMAGE = 1
PROJECTILE_PEW_HIT_REWARD = 0
PROJECTILE_PEW_POP_REWARD = 5

PROJECTILE_ROCKET_RECT_WIDTH = 5 * 12
PROJECTILE_ROCKET_RECT_HEIGHT = 4 * 12
PROJECTILE_ROCKET_RECT_COLOR = (0, 59, 255)
PROJECTILE_ROCKET_ANIMATIONS = [Sprite.load("textures/rocket_projectile.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
PROJECTILE_ROCKET_HORIZONTAL_SPEED = 3
PROJECTILE_ROCKET_VERTICAL_SPEED = 2
PROJECTILE_ROCKET_HEALTH = 1
PROJECTILE_ROCKET_DAMAGE = 10
PROJECTILE_ROCKET_HIT_REWARD = 0
PROJECTILE_ROCKET_POP_REWARD = 10

PROJECTILE_LASER_PARTS = 10
PROJECTILE_LASER_RECT_WIDTH = 12 * 12 * PROJECTILE_LASER_PARTS
PROJECTILE_LASER_RECT_HEIGHT = 1 * 12
PROJECTILE_LASER_RECT_COLOR = (0, 59, 255)
PROJECTILE_LASER_ANIMATIONS = [Sprite.load("textures/laser.png", SPRITE_SMALL_WIDTH * PROJECTILE_LASER_PARTS, SPRITE_SMALL_HEIGHT)]
PROJECTILE_LASER_DAMAGE = 20
PROJECTILE_LASER_PARTS = 10
PROJECTILE_LASER_LIFE = 4000

# █ ▀█▀ █▀▀ █▀▄▀█ █▀
# █ ░█░ ██▄ █░▀░█ ▄█

EYE_ORB_RECT_WIDTH = 8 * 12
EYE_ORB_RECT_HEIGHT = 7 * 12
EYE_ORB_RECT_COLOR = (135, 206, 235)
EYE_ORB_ANIMATIONS = [Sprite.load("textures/eye_orb1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/eye_orb2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/eye_orb3.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/eye_orb4.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
EYE_ORB_ANIMATIONS_INTERVAL = 100
EYE_ORB_HORIZONTAL_SPEED = 2
EYE_ORB_VERTICAL_SPEED = 0
EYE_ORB_ROCKETS_REWARD = 3
EYE_ORB_LASERS_REWARD = 2
EYE_ORB_HEALTH_REWARD = 2

# █▀█ ▀█▀ █░█ █▀▀ █▀█ █▀
# █▄█ ░█░ █▀█ ██▄ █▀▄ ▄█

POP_RECT_WIDTH = 5 * 12
POP_RECT_HEIGHT = 5 * 12
POP_RECT_COLOR = (0, 100, 0)
POP_ANIMATIONS = [Sprite.load("textures/pop1.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT), Sprite.load("textures/pop2.png", SPRITE_SMALL_WIDTH, SPRITE_SMALL_HEIGHT)]
POP_DURATION = 100

BATTLE_SHIP_SHIELD_RECT_WIDTH = 13 * 12
BATTLE_SHIP_SHIELD_RECT_HEIGHT = 10 * 12 - 4
BATTLE_SHIP_SHIELD_RECT_COLOR = (255, 192, 203)
BATTLE_SHIP_SHIELD_ANIMATIONS = [Sprite.load("textures/battleship_shield1.png", 16 * 12, 16 * 12), Sprite.load("textures/battleship_shield2.png", 16 * 12, 16 * 12)]
BATTLE_SHIP_SHIELD_ANIMATIONS_INTERVAL = 100
BATTLE_SHIP_SHIELD_DURATION = 5000

VOID_WALLPAPER = Sprite.load("textures/wallpapers/void.png", WINDOW_WIDTH, WINDOW_HEIGHT)
SKY_WALLPAPER = Sprite.load("textures/wallpapers/sky.png", WINDOW_WIDTH, WINDOW_HEIGHT)
MOUNTAINS_WALLPAPER = Sprite.load("textures/wallpapers/mountains.png", WINDOW_WIDTH, WINDOW_HEIGHT)
CITY_WALLPAPER = Sprite.load("textures/wallpapers/city.png", WINDOW_WIDTH, WINDOW_HEIGHT)
CURSED_WALLPAPER = Sprite.load("textures/wallpapers/cursed.png", WINDOW_WIDTH, WINDOW_HEIGHT)
CURSED2_WALLPAPER = Sprite.load("textures/wallpapers/cursed2.png", WINDOW_WIDTH, WINDOW_HEIGHT)
ROAD_WALLPAPER = Sprite.load("textures/wallpapers/road.png", WINDOW_WIDTH, WINDOW_HEIGHT)
ROAD2_WALLPAPER = Sprite.load("textures/wallpapers/road2.png", WINDOW_WIDTH, WINDOW_HEIGHT)

WEAPON_ROCKET = 0
WEAPON_LASER = 1

PLAYER_SPAWN_X = MAP_LEFT_BOUND + 25
PLAYER_SPAWN_Y = MAP_TOP_BOUND + (WINDOW_HEIGHT - MAP_TOP_BOUND - (WINDOW_HEIGHT - MAP_BOTTOM_BOUND) - BATTLE_SHIP_RECT_HEIGHT) // 2
PLAYER_DEFAULT_WEAPON = WEAPON_ROCKET
PLAYER_SPEED = 5
PLAYER_BASE_LIVES = 3
PLAYER_BASE_SCORE = 0
PLAYER_BASE_ROCKETS = 3
PLAYER_BASE_LASERS = 0
PLAYER_FLIGHT_ACCELERATION = 0.05
PLAYER_FLIGHT_MAX_SPEED = 50
PLAYER_HOLD_SHOOT_DELAY = 250

ROCKETS_REWARD = 0
LASER_REWARD = 1
HEALTH_REWARD = 2

# The default distance between MAP_LEFT_BOUND or MAP_RIGHT_BOUND (depending on horizontal_direction) which Bouncy entities stop moving horizontally
BOUNCY_DEFAULT_HORIZONTAL_STOP_DISTANCE = 2147483648
BOUNCY_DEFAULT_VERTICAL_STOP_SPEED = 4
ENEMY_SHOOT_ROLL_INTERVAL = 1000
BOSS_ENEMY_DAMAGE_BLINK_DURATION = 75

UP = "up"
LEFT = "left"
RIGHT = "right"
DOWN = "down"

TAG_ENEMY = "enemy"
TAG_PROJECTILE_PLAYER = "projectile_player"
TAG_PROJECTILE_ENEMY = "projectile_enemy"

NOKIA_LIGHT = "nokia_light"
NOKIA_DARK = "nokia_dark"
NOKIA_LIGHT_COLOR = (128, 183, 146)
NOKIA_DARK_COLOR = (0, 0, 0)

FONT_RECT_COLOR = (186, 85, 211)

FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_WIDTH = 8 * 3
FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_HEIGHT = 5 * 3
FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_GAP = 1 * 3
FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS = TextureAtlas(
    "textures/fonts/space_impact_counters.png", 
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_WIDTH, 
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_HEIGHT, 
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_GAP
)

FONT_SPACE_IMPACT_COUNTERS_CHAR_MAP = {
    "0": {"coords": (0, 0), "width": 9},
    "1": {"coords": (1, 0), "width": 9},
    "2": {"coords": (2, 0), "width": 9},
    "3": {"coords": (3, 0), "width": 9},
    "4": {"coords": (0, 1), "width": 9},
    "5": {"coords": (1, 1), "width": 9},
    "6": {"coords": (2, 1), "width": 9},
    "7": {"coords": (3, 1), "width": 9},
    "8": {"coords": (0, 2), "width": 9},
    "9": {"coords": (1, 2), "width": 9},
    "v": {"coords": (2, 2), "width": 15},
    ">": {"coords": (3, 2), "width": 16},
    "-": {"coords": (0, 3), "width": 9},
    "T": {"coords": (1, 3), "width": 9}
}

FONT_SPACE_IMPACT_COUNTERS = Font(
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS, 
    FONT_SPACE_IMPACT_COUNTERS_CHAR_MAP, 
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_WIDTH,
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_HEIGHT,
    FONT_SPACE_IMPACT_COUNTERS_TEXTURE_ATLAS_CHAR_GAP
)

FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_WIDTH = 5
FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_HEIGHT = 10
FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_GAP = 1
FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS = TextureAtlas(
    "textures/fonts/space_impact_menus.png", 
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_WIDTH, 
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_HEIGHT, 
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_GAP
)

FONT_SPACE_IMPACT_MENUS_CHAR_MAP = {
    "A": {"coords": (0, 0), "width": 5},
    "B": {"coords": (1, 0), "width": 5},
    "C": {"coords": (2, 0), "width": 5},
    "D": {"coords": (3, 0), "width": 5},
    "E": {"coords": (4, 0), "width": 5},
    "F": {"coords": (5, 0), "width": 5},
    "G": {"coords": (6, 0), "width": 5},
    "H": {"coords": (7, 0), "width": 5},
    "I": {"coords": (8, 0), "width": 5},
    "J": {"coords": (9, 0), "width": 5},
    "K": {"coords": (10, 0), "width": 5},
    "L": {"coords": (11, 0), "width": 5},
    "M": {"coords": (12, 0), "width": 5},
    "N": {"coords": (13, 0), "width": 5},
    "O": {"coords": (14, 0), "width": 5},
    "P": {"coords": (15, 0), "width": 5},
    "Q": {"coords": (16, 0), "width": 5},
    "R": {"coords": (17, 0), "width": 5},
    "S": {"coords": (18, 0), "width": 5},
    "T": {"coords": (19, 0), "width": 5},
    "U": {"coords": (20, 0), "width": 5},
    "V": {"coords": (21, 0), "width": 5},
    "W": {"coords": (22, 0), "width": 5},
    "X": {"coords": (23, 0), "width": 5},
    "Y": {"coords": (24, 0), "width": 5},
    "Z": {"coords": (25, 0), "width": 5},

    "a": {"coords": (0, 1), "width": 5},
    "b": {"coords": (1, 1), "width": 5},
    "c": {"coords": (2, 1), "width": 5},
    "d": {"coords": (3, 1), "width": 5},
    "e": {"coords": (4, 1), "width": 5},
    "f": {"coords": (5, 1), "width": 5},
    "g": {"coords": (6, 1), "width": 5},
    "h": {"coords": (7, 1), "width": 5},
    "i": {"coords": (8, 1), "width": 5},
    "j": {"coords": (9, 1), "width": 5},
    "k": {"coords": (10, 1), "width": 5},
    "l": {"coords": (11, 1), "width": 5},
    "m": {"coords": (12, 1), "width": 5},
    "n": {"coords": (13, 1), "width": 5},
    "o": {"coords": (14, 1), "width": 5},
    "p": {"coords": (15, 1), "width": 5},
    "q": {"coords": (16, 1), "width": 5},
    "r": {"coords": (17, 1), "width": 5},
    "s": {"coords": (18, 1), "width": 5},
    "t": {"coords": (19, 1), "width": 5},
    "u": {"coords": (20, 1), "width": 5},
    "v": {"coords": (21, 1), "width": 5},
    "w": {"coords": (22, 1), "width": 5},
    "x": {"coords": (23, 1), "width": 5},
    "y": {"coords": (24, 1), "width": 5},
    "z": {"coords": (25, 1), "width": 5},

    "0": {"coords": (0, 2), "width": 5},
    "1": {"coords": (1, 2), "width": 5},
    "2": {"coords": (2, 2), "width": 5},
    "3": {"coords": (3, 2), "width": 5},
    "4": {"coords": (4, 2), "width": 5},
    "5": {"coords": (5, 2), "width": 5},
    "6": {"coords": (6, 2), "width": 5},
    "7": {"coords": (7, 2), "width": 5},
    "8": {"coords": (8, 2), "width": 5},
    "9": {"coords": (9, 2), "width": 5},

    " ": {"coords": (10, 2), "width": 5},
    "-": {"coords": (11, 2), "width": 5},
    ":": {"coords": (12, 2), "width": 5}
}

FONT_SPACE_IMPACT_MENUS = Font(
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS, 
    FONT_SPACE_IMPACT_MENUS_CHAR_MAP, 
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_WIDTH,
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_HEIGHT,
    FONT_SPACE_IMPACT_MENUS_TEXTURE_ATLAS_CHAR_GAP
)

LIVES_TEXT_TOP_OFFSET = 25
LIVES_TEXT_FONT_SIZE = 3
LIVES_TEXT_ABSOLUTE_WIDTH = Text.width_of("vvv", FONT_SPACE_IMPACT_COUNTERS, LIVES_TEXT_FONT_SIZE)

WEAPON_TEXT_TOP_OFFSET = 25
WEAPON_TEXT_FONT_SIZE = 3
WEAPON_TEXT_ABSOLUTE_WIDTH = Text.width_of(">00", FONT_SPACE_IMPACT_COUNTERS, WEAPON_TEXT_FONT_SIZE)

SCORE_TEXT_TOP_OFFSET = 25
SCORE_TEXT_FONT_SIZE = 3

GAME_OVER_TEXT = "Game Over"
GAME_OVER_TEXT_FONT_SIZE = 10
GAME_OVER_SCORE_TEXT = "Your score:"
GAME_OVER_SCORE_TEXT_FONT_SIZE = 10
GAME_OVER_SCORE_VALUE_TEXT = "ABC123:-gtyyx"
GAME_OVER_SCORE_VALUE_TEXT_FONT_SIZE = 10

# Use 16bit numbers for counters such as score, health and rockets. If False, uses 32bit integers
USE_16BIT_INTEGERS = True
# Freezes the score on overflow.
FREEZE_SCORE_ON_OVERFLOW = False
# Shows the rects of the GameObjects. [⚠] Use only for debugging
DEBUG_SHOW_RECTS = False
# Displays the health bar above enemies. [⚠] Use only for debugging
DEBUG_SHOW_HEALTH_BARS = False
HEALTH_BAR_HEIGHT = 10
HEALTH_BAR_OFFSET_Y = HEALTH_BAR_HEIGHT + 20
HEALTH_BAR_UNDER_COLOR = (128, 128, 128)
HEALTH_BAR_OVER_COLOR = (255, 0, 0)
# Shows a rect representing the game field. [⚠] Use only for debugging
DEBUG_SHOW_MAP_BOUNDS = False